version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 39333:9333
      - 19333:19333
      - 39324:9324
    command: 'master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324'
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 38080:8080
      - 18080:18080
      - 39325:9325

    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 38888:8888
      - 18888:18888
      - 39326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 38333:8333
      - 39327:9327
    volumes:
      - ./data-center/seaweedfs:/etc/seaweedfs
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327 -config=/etc/seaweedfs/s3.conf'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 37333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 39000:9090
    volumes:
      - ./data-center/prometheus:/etc/prometheus
    command: --web.enable-lifecycle # --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
